tap "FelixKratz/formulae"
brew "sketchybar"
brew "borders"
cask "nikitabobko/tap/aerospace"

cask "wezterm"
brew "tmux"
brew "fzf"
brew "bat"
brew "neovim"

brew "mise"

brew "git"
brew "gh"
brew "act"
brew "oha"
brew "ansible"
brew "terraform"
brew "imagemagick"

cask "docker"
cask "jetbrains-toolbox"
cask "postman"
cask "figma"
cask "nordlayer"
cask "1password"
cask "notion"
cask "clickup"
cask "microsoft-office"
cask "brave-browser"
cask "google-chrome"
cask "responsively"
